name: Check
on: push
jobs:
  test:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: nimble-${{ hashFiles('*.nimble') }}

      - uses: jiro4989/setup-nim-action@v1
        with:
          # due to a bug with iterators, need version >= 1.5.1
          nim-version: devel

      - name: check formatting
        run: |
          nimble fmt
          if [ -z "$(git status -s)" ]; then
            echo "Found unformatted files" >&2 
            exit 1
          fi

      - name: Run tests
        run: nimble test -y

        
